# Generated by Django 3.2.7 on 2024-07-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0024_auto_20220606_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlindCarbonCopy',
        ),
    ]
