# Generated by Django 3.2.7 on 2024-07-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0167_quote_quoteexam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
