# Generated by Django 3.2.7 on 2024-07-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0168_rename_created_date_quote_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteexam',
            name='isRecommended',
            field=models.BooleanField(default=False),
        ),
    ]
