# Generated by Django 3.2.7 on 2024-07-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0169_quoteexam_isrecommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
