# Generated by Django 3.2.7 on 2024-07-18 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0170_quote_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreListed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='unit_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='responsible',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.customer'),
        ),
        migrations.CreateModel(
            name='PreListedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.exam')),
                ('preListed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.prelisted')),
            ],
        ),
    ]
