# Generated by Django 3.2.7 on 2024-08-07 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0171_auto_20240718_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryformAttachedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.casefile')),
            ],
        ),
        migrations.CreateModel(
            name='Outsource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.analysisform')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.servicecomment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='entryform',
            name='attached_files',
        ),
        migrations.AddField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='backend.customer'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OutsourceAttachedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachedFiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.entryformattachedfiles')),
                ('outsource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.outsource')),
            ],
        ),
        migrations.AddField(
            model_name='entryformattachedfiles',
            name='entryform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.entryform'),
        ),
    ]
