# Generated by Django 3.2.7 on 2024-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0172_auto_20240807_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='attached_files',
            field=models.ManyToManyField(blank=True, through='backend.EntryformAttachedFiles', to='backend.CaseFile'),
        ),
        migrations.AlterModelTable(
            name='entryformattachedfiles',
            table='backend_entryform_attached_files',
        ),
    ]
