# Generated by Django 3.2.7 on 2024-08-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0174_auto_20240812_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryform',
            name='center_index',
        ),
        migrations.AddField(
            model_name='entryform',
            name='company_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.customercenter'),
        ),
    ]
