# Generated by Django 3.2.7 on 2024-08-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0175_auto_20240813_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='company_index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_index', to='backend.customer'),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='backend.customer'),
        ),
    ]
