# Generated by Django 3.2.7 on 2024-08-27 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0177_weightgeneralscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisoptionalresult',
            name='resultOrgan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.resultorgan', verbose_name='result'),
        ),
    ]
